// next/src/components/ConnectWallet.tsx
import { useWalletStore } from "@/context/WalletContextProvider";
import React from "react";

type Props = {};

const ConnectWallet = (props: Props) => {
  const { connectWallet, injectiveAddress } = useWalletStore();
  const btnText = injectiveAddress
    ? `${injectiveAddress.slice(0, 5)}...${injectiveAddress.slice(-3)}`
    : "Connect Wallet";
  return (
    <button
      onClick={connectWallet}
      className='btn'
    >
      {btnText}
    </button>
  );
};

export default ConnectWallet;

// components/ConnectWallet.vue
<script setup>
import { useWalletStore } from "~~/store/wallet";

const walletStore = useWalletStore();

const injAddressShort = computed(
  () =>
    `${walletStore.injectiveAddress.slice(
      0,
      6
    )}...${walletStore.injectiveAddress.slice(-3)}`
);

function handleClick() {
  walletStore.connectWallet().catch(alert);
}
</script>

<template>
  <Button v-if="walletStore.injectiveAddress">{{ injAddressShort }}</Button>
  <Button
    v-else
    @click="handleClick"
  >
    Connect Wallet
  </Button>
</template>
